stages:
    - build
    - test
    - deploy

build::linux:
    stage: build
    tags: 
        - shyft
        - linux
        
    script:
        - "echo Using ${SHYFT_DEPENDENCIES_DIR}"
        - "echo Path ${PATH}"
        - conda activate base
        - "mkdir -p build"
        - "cd build&&cmake .."
        - "make -j 4 VERBOSE=0"
        - make install

    artifacts:
        name: binaries-linux
        expire_in: 2 day
        paths:
            - build/test/test_shyft
            - shyft/api/_api.so
            - shyft/api/pt_gs_k/_pt_gs_k.so
            - shyft/api/pt_hps_k/_pt_hps_k.so
            - shyft/api/pt_hs_k/_pt_hs_k.so
            - shyft/api/pt_ss_k/_pt_ss_k.so
            - shyft/api/r_pm_gs_k/_r_pm_gs_k.so
            - shyft/api/hbv_stack/_hbv_stack.so
            - shyft/lib/



build::win64:
    stage: build
    tags:
        - shyft
        - win64
    script:
        - "echo Using $SHYFT_DEPENDENCIES"
        - "echo Path $PATH"
        - "build_support/win_build_shyft.cmd"

    artifacts:
        name: binaries-win64
        expire_in: 2 day
        paths:
            - bin/Release/test_shyft.exe
            - shyft/api/_api.pyd
            - shyft/api/pt_gs_k/_pt_gs_k.pyd
            - shyft/api/pt_hps_k/_pt_hps_k.pyd
            - shyft/api/pt_hs_k/_pt_hs_k.pyd
            - shyft/api/pt_ss_k/_pt_ss_k.pyd
            - shyft/api/r_pm_gs_k/_r_pm_gs_k.pyd
            - shyft/api/hbv_stack/_hbv_stack.pyd

test::win64:
    stage: test
    tags:
        - shyft
        - win64
    dependencies:
        - build::win64
    script:
        - echo starting the tests
        - "bin\\Release\\test_shyft.exe"
        - "set PYTHONPATH=."
        - "nosetests shyft/tests --with-coverage --cover-html-dir=py_cover --cover-html --cover-package=shyft.repository --cover-package=shyft.orchestration --cover-package=shyft.api"
        - "coverage report -m"
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
        name: python_coverage_report
        paths:
            - py_cover
        expire_in: 2 week


test::linux:
    stage: test
    tags:
        - shyft
        - linux
    dependencies:
        - build::linux
    script:
        - build/test/test_shyft
        - conda activate shyft_env
        - "PYTHONPATH=. nosetests shyft/tests --with-coverage --cover-html-dir=py_cover --cover-html --cover-package=shyft.repository --cover-package=shyft.orchestration --cover-package=shyft.api"
        - coverage report -m
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
    artifacts:
        name: python_coverage_report
        paths:
            - py_cover
        expire_in: 2 week

deploy::win64:
    stage: deploy
    #only:
    #    - master
    tags:
        - shyft
        - win64
    dependencies:
        - build::win64
        - test::win64
    script:
        - "echo %CI_COMMIT_REF_NAME%"
        - "build_support/win_conda_deploy.cmd  %CI_COMMIT_REF_NAME%"

deploy::linux:
    stage: deploy
    #only:
    #    - master
    tags:
        - shyft
        - linux
    dependencies:
        - build::linux
        - test::linux
    script:
        - conda activate base
        - 'np_version=`python -c "import numpy;print(numpy.version.version[:-2])"`'
        - "export SHYFT_VERSION=4.6.`git rev-list HEAD --count`"
        - "echo ${SHYFT_VERSION}>VERSION"
        - "echo ${SHYFT_VERSION} ${np_version}"
        - "conda build --numpy ${np_version} --no-test --no-copy-test-source-files --label ${CI_COMMIT_REF_NAME} conda_recipe"